name: CircuitDetector
main: io.github.netdex.CircuitDetector.CircuitDetector
version: 1.1

commands:
  cd:
    description: The default CircuitDetector command.
    usage: "Usage: /cd help"
    permission: CircuitDetector.cd
    permission-message: You don't have permission to use this command.